apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: user-service
build:
  artifacts:
    - image: ecosystem/user-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - /k8/*.yaml

