apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: leaderboard-service
build:
  artifacts:
  - image: ecosystem/leaderboard-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - /k8/*.yaml
