server:
  port: 9093

spring:
  application:
    name: gamification-service

  zipkin:
    enabled: true
    base-url: http://my-zipkin-collector:9411/

  sleuth:
    sampler:
      percentage: 1.0

  kafka:
      bootstrap-servers: localhost:9092

kafkaconfig:
  topic: leaderboard
  groupId: ecosystem
  partitionCount: 1
  retries: 3
  autoCommitEnabled: false