server:
  port: 9092

spring:
  application:
    name: user-service

  zipkin:
    enabled: true
    base-url: http://my-zipkin-collector:9411/

  sleuth:
    sampler:
      percentage: 1.0