apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ecosystem
deploy:
  kubectl:
    manifests:
    - nginx-ingress/nginx.deployment.yaml
    - nginx-ingress/cloud-generic.yaml
    - nginx-ingress/ingress.yaml
