server:
  port: 9094

spring:
  application:
    name: leaderboard-service

  zipkin:
    enabled: true
    base-url: http://my-zipkin-collector:9411/

  sleuth:
    sampler:
      percentage: 1.0

  kafka:
    groupId: ecosystem
    bootstrap-servers: my-cluster-kafka-bootstrap:9092
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
      group-id: ecosystem
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topics:
  leaderboard: leaderboard